apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-micrometer
  name: echo-micrometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-micrometer
  strategy: {}
  template:
    metadata:
      labels:
        app: echo-micrometer
    spec:
      containers:
      - image: nontster/echo-micrometer:0.0.1-SNAPSHOT
        name: echo-micrometer
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: 2048Mi
            cpu: 500m
          requests:
            memory: 150Mi
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3