iapiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: backend
  name: echo-micrometer
spec:
  endpoints:
  - interval: 10s
    path: /actuator/prometheus
    port: http
  selector:
    matchLabels:
      app: echo-micrometer